apiVersion: v1
kind: Secret
metadata:
  name: {{ include "paradise-plants.fullname" . }}-backend
  labels:
    app: {{ include "paradise-plants.fullname" . }}
    component: backend
type: Opaque
stringData:
  db-password: "{{ .Values.backend.database.password }}"
